import type { Metadata } from "next";
import "./globals.css";
import MainPage from "./page";

export const metadata: Metadata = {
  title: "MHVS - Backoffice",
  description: "Generated by MHVS",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <MainPage>{children}</MainPage>
      </body>
    </html>
  );
}
